name: cdk workflow

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  # Github Actionsを実行しているリポジトリ名を取得
  GIT_REPO: ${{ github.repository }}

jobs:
  initialize:
    runs-on: ubuntu-latest
    permissions: read-all
    outputs:
      infra_changed: ${{ steps.filter.outputs.infra }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # infraディレクトリ以下のファイル変更を検知
      - name: Detect File Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.event.before }}
          filters: |
            infra:
              - 'infra/bin/**'
              - 'infra/lib/**'

  deploy:
    runs-on: ubuntu-latest
    needs: [initialize]
    # infraディレクトリ以下のファイル変更があった場合のみデプロイを実行
    if: |
      github.event_name == 'push' &&
      needs.initialize.outputs.infra_changed == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: npm install
        shell: bash
        run: |
          npm install
        working-directory: infra

      - name: Set Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1

      - name: Run CDK Deploy
        run: |
          npm run cdk:diff -- -c isFirst=n
        working-directory: infra
